// <auto-generated />
using System;
using ITHS_DB_Lab4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITHS_DB_Lab4.Migrations
{
    [DbContext(typeof(ExersiceContext))]
    [Migration("20191210225019_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITHS_DB_Lab4.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("PainLevel");

                    b.Property<int?>("Repetitions");

                    b.Property<int>("SessionId");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("SessionId");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Gear");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PersonId");

                    b.Property<float>("Time");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Session");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Session");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Cycling", b =>
                {
                    b.HasBaseType("ITHS_DB_Lab4.Session");

                    b.HasDiscriminator().HasValue("Cycling");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Running", b =>
                {
                    b.HasBaseType("ITHS_DB_Lab4.Session");

                    b.HasDiscriminator().HasValue("Running");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Swiming", b =>
                {
                    b.HasBaseType("ITHS_DB_Lab4.Session");

                    b.HasDiscriminator().HasValue("Swiming");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Exercise", b =>
                {
                    b.HasOne("ITHS_DB_Lab4.Session", "Session")
                        .WithMany("Exercises")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Gear", b =>
                {
                    b.HasOne("ITHS_DB_Lab4.Session", "Session")
                        .WithMany("Gear")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Session", b =>
                {
                    b.HasOne("ITHS_DB_Lab4.Person", "Person")
                        .WithMany("Sessions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
